nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': 
            allow_credentials: false
            allow_origin: ['http://volyvolt.org','^http://localhost:[0-9]+','^https://192.168.137.1:[0-9]+','*']       
            allow_headers: ['X-Custom-Auth', 'x-auth','Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
